Import('env')

env = env.Clone() 

blosc_files = ["blosc.c", "blosc_filter.c", \
               "blosclz.c", "shuffle.c", \
               "shuffle-generic.c",  "bitshuffle-generic.c", \
               "shuffle-sse2.c", "bitshuffle-sse2.c" ]
blosc_files = [ "util/blosc/" + x for x in blosc_files ]

env.Library('blosc', blosc_files)
env.Library('triangular', ["triangular/dimer.cxx"])
env.Library('graph', ["graph/graph.cxx", "graph/bcc_lattice.cxx"])

env.Program('dimer_sim', ['triangular/dimer_sim.cxx'], LIBS=['blosc', 'triangular'], LIBPATH=['.'] + env['CPPPATH'])
env.Program('graph_sim', ['graph/graph_simulation.cxx'], LIBS=['blosc', 'graph'], LIBPATH=['.'] + env['CPPPATH'])

Export('env')
env.SConscript('test/SConscript')
